version: '3'

services:
  web:
    image: node:10
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm run start 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
      - SERVER_PORT=3000
    links:
      - "redis"
  redis:
    image: redis:6
    ports:
      - "6379"